=== l-pommeret/EDT-LOGOS1/calendars.schema.json
{
  "$id": "TODO",
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalItems": false,
  "description": "The root schema comprises the entire JSON document.",
  "examples": [
    [
      {
        "code": 6552,
        "label": "supr/modifiés",
        "parcours": "mathinfo",
        "title": "AncVersion",
        "year": "l1"
      },
      {
        "code": 6699,
        "label": "groupe 1",
        "parcours": "mathinfo",
        "title": "MathInfo 1",
        "year": "l1"
      }
    ]
  ],
  "items": {
    "additionalProperties": false,
    "properties": {
      "annexe": {
        "description": "Définit si un groupe est considéré comme 'annexe' ou pas.",
        "title": "Annexe",
        "type": "boolean"
      },
      "code": {
        "description": "Le code ADE du groupe.",
        "title": "Code",
        "type": [
          "integer",
          "string"
        ]
      },
      "initialDate": {
        "description": "La première date qui doit être affichée dans le calendrier pour ce groupe.",
        "title": "Date initiale",
        "type": "string"
      },
      "label": {
        "description": "Un nom court à afficher dans les boutons et autres.",
        "examples": [
          "groupe 2"
        ],
        "title": "Nom affiché",
        "type": "string"
      },
      "page": {
        "description": "La liste des pages sur lesquelles ce groupe doit apparaître.",
        "title": "Pages",
        "type": "array",
        "examples": [
          "licence",
          "lcao"
        ],
        "items": {
          "type": "string"
        }
      },
      "parcours": {
        "description": "Le code du parcours (filière sans l'année) du cours.",
        "examples": [
          "mathinfo",
          "math"
        ],
        "title": "Parcours",
        "type": "string"
      },
      "title": {
        "description": "Le titre du groupe, contient le parcours et l'année.",
        "examples": [
          "MathInfo 1"
        ],
        "title": "Titre",
        "type": "string"
      },
      "year": {
        "description": "Le code de l'année du groupe.",
        "examples": [
          "l1",
          "l2"
        ],
        "title": "Année",
        "type": "string"
      }
    },
    "required": [
      "code",
      "title",
      "label",
      "parcours",
      "year"
    ]
  },
  "title": "Schema for calendars",
  "type": "array"
}

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-sdv.json
[
   {"code": "43849", "title": "Diversite et evolution des organismes vivants", "label": "Divers.Evo.", "parcours": "sdv", "year": "s1"} ,
   {"code": "43912", "title": "Methodologies", "label": "Metho.", "parcours": "sdv", "year": "s1"} ,
   {"code": "43875", "title": "Modelisation mathematique en biologie", "label": "Mod.Math", "parcours": "sdv", "year": "s1"} ,
   {"code": "43879", "title": "Modelisation mathematique en biologie CM01", "label": "CM Section1", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43876", "title": "Modelisation mathematique en biologie CM02", "label": "CM Section2", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43881", "title": "Modelisation mathematique en biologie TD01", "label": "TD01", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43885", "title": "Modelisation mathematique en biologie TD02", "label": "TD02", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43880", "title": "Modelisation mathematique en biologie TD03", "label": "TD03", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43882", "title": "Modelisation mathematique en biologie TD04", "label": "TD04", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43877", "title": "Modelisation mathematique en biologie TD05", "label": "TD05", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43883", "title": "Modelisation mathematique en biologie TD06", "label": "TD06", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43884", "title": "Modelisation mathematique en biologie TD07", "label": "TD07", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43878", "title": "Modelisation mathematique en biologie TD08", "label": "TD08", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "21987", "title": "Modelisation mathematique en biologie TDDL", "label": "TD DL", "parcours": "sdv", "year": "s1-mod math"} ,
   {"code": "43821", "title": "Physiologie cellulaire", "label": "Physio.", "parcours": "sdv", "year": "s1"} ,
   {"code": "43886", "title": "Thermochimie et equilibres en solution", "label": "Thermoch.", "parcours": "sdv", "year": "s1"} ,
   {"code": "44157", "title": "Biochimie des macromolecules biologiques", "label": "Biochi.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44260", "title": "Biodiversite marine en zone intertidale", "label": "Biodiv.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44071", "title": "Biologie cellulaire et moleculaire 2", "label": "Bio cell.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44281", "title": "Biologie des champignons", "label": "B.Champi.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44098", "title": "Biologie integrative animale et vegetale 1", "label": "B.Int.Anim.Veg.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44190", "title": "Biologie moleculaire et genetique 2", "label": "B.Mol&Gen", "parcours": "sdv", "year": "s3"} ,
   {"code": "44241", "title": "Biostatistiques 1 : probabilites, statistiques", "label": "Biostat1", "parcours": "sdv", "year": "s3"} ,
   {"code": "44314", "title": "Conference Interdisciplinaire", "label": "Conf.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44289", "title": "Construction du raisonnement scientifique", "label": "Raisonmt.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44298", "title": "Diversite du developpement chez les especes modeles animales", "label": "Diversite", "parcours": "sdv", "year": "s3"} ,
   {"code": "44311", "title": "Espace game moleculaire", "label": "Esp.G.Mol.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44292", "title": "Introduction a la medecine experimentale Claude Bernard", "label": "Intro.Med.Exp", "parcours": "sdv", "year": "s3"} ,
   {"code": "44295", "title": "Les bio-industries et leurs metiers", "label": "Bioindust.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44218", "title": "Mathematiques pour les biologistes", "label": "Math", "parcours": "sdv", "year": "s3"} ,
   {"code": "44225", "title": "Mathematiques pour les biologistes CM01", "label": "CM", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44226", "title": "Mathematiques pour les biologistes TD01", "label": "TD01", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44228", "title": "Mathematiques pour les biologistes TD02", "label": "TD02", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44227", "title": "Mathematiques pour les biologistes TD03", "label": "TD03", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44219", "title": "Mathematiques pour les biologistes TD04", "label": "TD04", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44220", "title": "Mathematiques pour les biologistes TD05", "label": "TD05", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44221", "title": "Mathematiques pour les biologistes TD06", "label": "TD06", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44222", "title": "Mathematiques pour les biologistes TD07", "label": "TD07", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44224", "title": "Mathematiques pour les biologistes TD08", "label": "TD08", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44223", "title": "Mathematiques pour les biologistes TD09", "label": "TD09", "parcours": "sdv", "year": "s3-math pr bio"} ,
   {"code": "44229", "title": "Reactivite et analyse de molecules biologiques", "label": "React&ana.", "parcours": "sdv", "year": "s3"} ,
   {"code": "44308", "title": "Sciences et societe", "label": "Sci&Soc", "parcours": "sdv", "year": "s3"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-phys.json
[
   {"code": "6361", "title": "Physique1", "label": "PHY1", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "6362", "title": "Physique2", "label": "PHY2", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "6363", "title": "Physique3", "label": "PHY3", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "6371", "title": "Physique4", "label": "PHY4", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "6639", "title": "Physique5", "label": "PHY5", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "39539", "title": "Rebon1", "label": "REB1", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "39540", "title": "Rebon2", "label": "REB2", "parcours": "phys", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-phyl1", "title": "AncVersion", "label": "obsolète", "parcours": "phys", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "11274", "title": "MEDPHY", "label": "MEDPHY", "parcours": "phys", "year": "l2", "page": ["licence"]} ,
   {"code": "6742", "title": "Physique1", "label": "PHY1", "parcours": "phys", "year": "l2", "page": ["licence"]} ,
   {"code": "6743", "title": "Physique2", "label": "PHY2", "parcours": "phys", "year": "l2", "page": ["licence"]} ,
   {"code": "6744", "title": "Physique3", "label": "PHY3", "parcours": "phys", "year": "l2", "page": ["licence"]} ,
   {"code": "6675", "title": "PHYTECH", "label": "PHYTECH", "parcours": "phys", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-phyl2", "title": "AncVersion", "label": "obsolète", "parcours": "phys", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "7866", "title": "L3 1-A", "label": "L3 1 - A", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7867", "title": "L3 1-B", "label": "L3 1 - B", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7868", "title": "L3 2-A", "label": "L3 2 - A", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7869", "title": "L3 2-B", "label": "L3 2 - B", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7870", "title": "L3 3-A", "label": "L3 3 - A", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7873", "title": "L3 3-B", "label": "L3 3 - B", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7871", "title": "L3 4-A", "label": "L3 4 - A", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "7874", "title": "L3 4-B", "label": "L3 4 - B", "parcours": "phys", "year": "l3-sem5", "page": ["licence"]} ,
   {"code": "obso-physl3-sem5", "title": "AncVersion", "label": "obsolète", "parcours": "phys", "year": "l3-sem5", "page": ["licence"], "annexe": true} ,
   {"code": "5312", "title": "L3 E 1", "label": "L3 E 1", "parcours": "phys", "year": "l3-sem6", "page": ["licence"]} ,
   {"code": "5313", "title": "L3 E 2", "label": "L3 E 2", "parcours": "phys", "year": "l3-sem6", "page": ["licence"]} ,
   {"code": "5498", "title": "L3 T 1", "label": "L3 T 1", "parcours": "phys", "year": "l3-sem6", "page": ["licence"]} ,
   {"code": "5499", "title": "L3 T 2", "label": "L3 T 2", "parcours": "phys", "year": "l3-sem6", "page": ["licence"]} ,
   {"code": "5500", "title": "L3 T 3", "label": "L3 T 3", "parcours": "phys", "year": "l3-sem6", "page": ["licence"]} ,
   {"code": "obso-physl3-sem6", "title": "AncVersion", "label": "obsolète", "parcours": "phys", "year": "l3-sem6", "page": ["licence"], "annexe": true} ,
   {"code": "6016", "title": "M1 Phys", "label": "M1-Appli", "parcours": "phys", "year": "m1-sem1", "page": ["licence"]} ,
   {"code": "6015", "title": "M1 Phys", "label": "M1-Fonda1", "parcours": "phys", "year": "m1-sem1", "page": ["licence"]} ,
   {"code": "4864", "title": "M1 Phys", "label": "M1-Fonda2", "parcours": "phys", "year": "m1-sem1", "page": ["licence"]} ,
   {"code": "obso-physm1s1", "title": "AncVersion", "label": "obsolète", "parcours": "phys", "year": "m1-sem1", "page": ["licence"], "annexe": true} ,
   {"code": "1040", "title": "Salles condorcet TP", "label": "TP073A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1251", "title": "Salles condorcet TP", "label": "TP075A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1293", "title": "Salles condorcet TP", "label": "TP077A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1016", "title": "Salles condorcet TP", "label": "TP156A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1571", "title": "Salles condorcet TP", "label": "TP172A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1541", "title": "Salles condorcet TP", "label": "TP173A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1458", "title": "Salles condorcet TP", "label": "TP174A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "959", "title": "Salles condorcet TP", "label": "TP176A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1636", "title": "Salles condorcet TP", "label": "TP192A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1413", "title": "Salles condorcet TP", "label": "TP193A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1354", "title": "Salles condorcet TP", "label": "TP250A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1047", "title": "Salles condorcet TP", "label": "TP276A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1294", "title": "Salles condorcet TP", "label": "TP285A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1066", "title": "Salles condorcet TP", "label": "TP292A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1565", "title": "Salles condorcet TP", "label": "TP293A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1468", "title": "Salles condorcet TP", "label": "TP294A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1343", "title": "Salles condorcet TP", "label": "TP313A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1543", "title": "Salles condorcet TP", "label": "TP322A", "parcours": "phys", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1028", "title": "Salles condorcet TP", "label": "TP338A", "parcours": "phys", "year": "salles TP", "page": ["licence"]}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-cupge.json
[
   {"code": "6532", "title": "CUPGE", "label": "CUPGE1", "parcours": "cupge", "year": "l1", "page": ["licence"]} ,
   {"code": "6533", "title": "CUPGE", "label": "CUPGE2", "parcours": "cupge", "year": "l1", "page": ["licence"]} ,
   {"code": "6534", "title": "DLPC", "label": "DLPC", "parcours": "cupge", "year": "l1", "page": ["licence"]} ,
   {"code": "11220", "title": "DLPM", "label": "DLPM", "parcours": "cupge", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-cupgel1", "title": "AncVersion", "label": "obsolète", "parcours": "cupge", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "6652", "title": "CUPGE", "label": "CUPGE1", "parcours": "cupge", "year": "l2", "page": ["licence"]} ,
   {"code": "6653", "title": "CUPGE", "label": "CUPGE2", "parcours": "cupge", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-cupgel2", "title": "AncVersion", "label": "obsolète", "parcours": "cupge", "year": "l2", "page": ["licence"], "annexe": true}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-dlp-cm.json
[
   {"code": "6534", "title": "DLPC", "label": "DLPC", "parcours": "dlp-cm", "year": "l1", "page": ["licence"]} ,
   {"code": "11220", "title": "DLPM", "label": "DLPM", "parcours": "dlp-cm", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-dlp-cml1", "title": "AncVersion", "label": "obsolète", "parcours": "dlp-cm", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "6147", "title": "L2DLPC", "label": "DLPC", "parcours": "dlp-cm", "year": "l2", "page": ["licence"]} ,
   {"code": "3465", "title": "L2DLPM", "label": "DLPM", "parcours": "dlp-cm", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-dlp-cml2", "title": "AncVersion", "label": "obsolète", "parcours": "dlp-cm", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "6489", "title": "DLPC", "label": "DLPC", "parcours": "dlp-cm", "year": "l3", "page": ["licence"]} ,
   {"code": "6491", "title": "DLPC", "label": "DLPC-GrA", "parcours": "dlp-cm", "year": "l3", "page": ["licence"]} ,
   {"code": "6492", "title": "DLPC", "label": "DLPC-GrB", "parcours": "dlp-cm", "year": "l3", "page": ["licence"]} ,
   {"code": "14337", "title": "L3DLPM", "label": "DLPM", "parcours": "dlp-cm", "year": "l3", "page": ["licence"]} ,
   {"code": "obso-dlp-cml3", "title": "AncVersion", "label": "obsolète", "parcours": "dlp-cm", "year": "l3", "page": ["licence"], "annexe": true}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-eidd.json
[
   {"code": "14225", "title": "1A_BI_FISA", "label": "1A BI FISA", "parcours": "eidd", "year": "1A-S5"} ,
   {"code": "14227", "title": "1A_FISE", "label": "1A FISE", "parcours": "eidd", "year": "1A-S5"} ,
   {"code": "14226", "title": "1A_GBM_FISA", "label": "1A GBM FISA", "parcours": "eidd", "year": "1A-S5"} ,
   {"code": "14309", "title": "1A_BI_FISA", "label": "1A BI-FISA", "parcours": "eidd", "year": "1A-S6"} ,
   {"code": "14310", "title": "1A_GBM_FISA", "label": "1A GBM-FISA", "parcours": "eidd", "year": "1A-S6"} ,
   {"code": "14313", "title": "1A_GP", "label": "1A GP", "parcours": "eidd", "year": "1A-S6"} ,
   {"code": "14314", "title": "1A_MN", "label": "1A MN", "parcours": "eidd", "year": "1A-S6"} ,
   {"code": "14311", "title": "1A_SIE", "label": "1A SIE", "parcours": "eidd", "year": "1A-S6"} ,
   {"code": "14317", "title": "2A_BI_FISA", "label": "2A BI-FISA", "parcours": "eidd", "year": "2A"} ,
   {"code": "14318", "title": "2A_BI_FISE", "label": "2A BI-FISE", "parcours": "eidd", "year": "2A"} ,
   {"code": "14322", "title": "2A_GP", "label": "2A GP", "parcours": "eidd", "year": "2A"} ,
   {"code": "14325", "title": "3A_GP", "label": "3A GP", "parcours": "eidd", "year": "3A"} ,
   {"code": "14327", "title": "2A_MN", "label": "2A MN", "parcours": "eidd", "year": "2A"} ,
   {"code": "14329", "title": "3A_MN", "label": "3A MN", "parcours": "eidd", "year": "3A"} ,
   {"code": "14331", "title": "2A_SIE", "label": "2A SIE", "parcours": "eidd", "year": "2A"} ,
   {"code": "14333", "title": "3A_SIE", "label": "3A SIE", "parcours": "eidd", "year": "3A"} ,
   {"code": "14320", "title": "3A_BI_FISA", "label": "3A BI-FISA", "parcours": "eidd", "year": "3A"} ,
   {"code": "14321", "title": "3A_BI_FISE", "label": "3A BI-FISE", "parcours": "eidd", "year": "3A"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-mathens.json
[
   {"code": "AnglaisL3ufrmath.1", "title": "L3MFA Anglais", "label": "Angl.1", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.2", "title": "L3MFA Anglais", "label": "Angl.2", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.3", "title": "L3MFA Anglais", "label": "Angl.3", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.4", "title": "L3MFA Anglais", "label": "Angl.4", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.5", "title": "L3MFA Anglais", "label": "Angl.5", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.6", "title": "L3MFA Anglais", "label": "Angl.6", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "47465", "title": "MathEns", "label": "MathEns1", "parcours": "mathens", "year": "l3", "page": ["licence"]} ,
   {"code": "obso-mathensl3", "title": "AncVersion", "label": "obsol√®te", "parcours": "mathens", "year": "l3", "page": ["licence"], "annexe": true} ,
   {"code": "28473", "title": "M1 Maths MEEF", "label": "M1 MEEF", "parcours": "mathens", "year": "m1", "page": ["licence"]} ,
   {"code": "28494", "title": "M2 Maths MEEF", "label": "M2 MEEF", "parcours": "mathens", "year": "m2", "page": ["licence"]} ,
   {"code": "28281", "title": "M2 DIDACTIQUE SCIENCES - DIDACTIQUE MATHEMATIQUES - GM", "label": "M2 DID Maths", "parcours": "mathens", "year": "m2"} ,
   {"code": "28315", "title": "M2 DIDACTIQUE SCIENCES - DIDAC FORM (MATH SCIEN NAT) - GM", "label": "M2 DID M-SN", "parcours": "mathens", "year": "m2"} ,
   {"code": "28255", "title": "M2 DIDACTIQUE SCIENCES - DIDACTIQUE HISTOIRE ET GEO - GM", "label": "M2 DiID HG", "parcours": "mathens", "year": "m2"} ,
   {"code": "28301", "title": "M2 DIDACTIQUE SCIENCES - DIDACTIQUE SCIENCES NATURE - GM", "label": "M2 DID SN", "parcours": "mathens", "year": "m2"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-info.json
[
   {"code": "14516", "title": "Informatique1", "label": "INFO1", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14517", "title": "Informatique2", "label": "INFO2", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14518", "title": "Informatique3", "label": "INFO3", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14521", "title": "Informatique4", "label": "INFO4", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14520", "title": "Informatique5", "label": "INFO5", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14519", "title": "Informatique6", "label": "INFO6", "parcours": "info", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "14525", "title": "Info/Bio", "label": "INFO BIO A", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14524", "title": "Info/Bio", "label": "INFO BIO B", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14523", "title": "Info/Jap", "label": "INFO JAP", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14381", "title": "MathInfo 1", "label": "MathInfo1", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "14383", "title": "MathInfo 2", "label": "MathInfo2", "parcours": "info", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-infol1", "title": "AncVersion", "label": "obsolète", "parcours": "info", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "14546", "title": "L2 Informatique1", "label": "INFO1", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14552", "title": "L2 Informatique2", "label": "INFO2", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14554", "title": "L2 Informatique3", "label": "INFO3", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14557", "title": "L2 Informatique4", "label": "INFO4", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14559", "title": "L2 Informatique5", "label": "INFO5", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14576", "title": "Info/Bio", "label": "INFO BIO", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "14575", "title": "Info/Jap", "label": "INFO JAP", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "22129", "title": "MathInfo1", "label": "MathInfo1", "parcours": "info", "year": "l2", "page": ["licence"]} ,
   {"code": "22130", "title": "MathInfo2", "label": "MathInfo2", "parcours": "info", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "obso-infol2", "title": "AncVersion", "label": "obsolète", "parcours": "info", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "14543", "title": "L3 info", "label": "INFO1", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14577", "title": "L3 info", "label": "INFO2", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14579", "title": "L3 info", "label": "INFO3", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14580", "title": "L3 info", "label": "INFO4", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14581", "title": "L3 info", "label": "INFO5", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14584", "title": "L3 info Bio", "label": "INFO BIO", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "14585", "title": "L3 info Jap", "label": "INFO JAP", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "22133", "title": "L3MathInfo1", "label": "INFO MATH", "parcours": "info", "year": "l3", "page": ["licence"]} ,
   {"code": "obso-infol3", "title": "AncVersion", "label": "obsolète", "parcours": "info", "year": "l3", "page": ["licence"], "annexe": true} ,
   {"code": "14599", "title": "M1 CRYPTO/MIC", "label": "M1 CRYPTO/MIC", "parcours": "info", "year": "m1"} ,
   {"code": "14588", "title": "M1 DATA", "label": "M1 DATA", "parcours": "info", "year": "m1"} ,
   {"code": "58594", "title": "M1 EIDD", "label": "M1 EIDD", "parcours": "info", "year": "m1"} ,
   {"code": "14590", "title": "M1 GENIAL", "label": "M1 GENIAL", "parcours": "info", "year": "m1"} ,
   {"code": "14589", "title": "M1 IMPAIRS", "label": "M1 IMPAIRS", "parcours": "info", "year": "m1"} ,
   {"code": "14595", "title": "M1 LP", "label": "M1 LP", "parcours": "info", "year": "m1"} ,
   {"code": "14596", "title": "M1 MPRI", "label": "M1 MPRI", "parcours": "info", "year": "m1"} ,
   {"code": "14602", "title": "M1 SDD/MIDS", "label": "M1 SDD/MIDS", "parcours": "info", "year": "m1"} ,
   {"code": "14617", "title": "M2 CRYPTO/MIC", "label": "M2 CRYPTO/MIC", "parcours": "info", "year": "m2"} ,
   {"code": "14620", "title": "M2 DATA", "label": "M2 DATA", "parcours": "info", "year": "m2"} ,
   {"code": "60821", "title": "M2 EIDD", "label": "M2 EIDD", "parcours": "info", "year": "m2"} ,
   {"code": "14627", "title": "M2 GENIAL", "label": "M2 GENIAL", "parcours": "info", "year": "m2"} ,
   {"code": "14623", "title": "M2 IMPAIRS", "label": "M2 IMPAIRS", "parcours": "info", "year": "m2"} ,
   {"code": "14622", "title": "M2 LP", "label": "M2 LP", "parcours": "info", "year": "m2"} ,
   {"code": "14626", "title": "M2 MPRI", "label": "M2 MPRI", "parcours": "info", "year": "m2"} ,
   {"code": "14629", "title": "M2 SDD/MIDS", "label": "M2 SDD/MIDS", "parcours": "info", "year": "m2"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-epc.json
[
   {"code": "6535", "title": "EPC", "label": "EPC", "parcours": "epc", "year": "l1", "page": ["licence"]} ,
   {"code": "6668", "title": "EPC", "label": "EPC", "parcours": "epc", "year": "l2", "page": ["licence"]} ,
   {"code": "11382", "title": "EPC", "label": "EPC", "parcours": "epc", "year": "l3", "page": ["licence"]}
]
