=== l-pommeret/EDT-LOGOS1/calendars.schema.json
{
  "$id": "TODO",
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalItems": false,
  "description": "The root schema comprises the entire JSON document.",
  "examples": [
    [
      {
        "code": 6552,
        "label": "supr/modifiés",
        "parcours": "mathinfo",
        "title": "AncVersion",
        "year": "l1"
      },
      {
        "code": 6699,
        "label": "groupe 1",
        "parcours": "mathinfo",
        "title": "MathInfo 1",
        "year": "l1"
      }
    ]
  ],
  "items": {
    "additionalProperties": false,
    "properties": {
      "annexe": {
        "description": "Définit si un groupe est considéré comme 'annexe' ou pas.",
        "title": "Annexe",
        "type": "boolean"
      },
      "code": {
        "description": "Le code ADE du groupe.",
        "title": "Code",
        "type": [
          "integer",
          "string"
        ]
      },
      "initialDate": {
        "description": "La première date qui doit être affichée dans le calendrier pour ce groupe.",
        "title": "Date initiale",
        "type": "string"
      },
      "label": {
        "description": "Un nom court à afficher dans les boutons et autres.",
        "examples": [
          "groupe 2"
        ],
        "title": "Nom affiché",
        "type": "string"
      },
      "page": {
        "description": "La liste des pages sur lesquelles ce groupe doit apparaître.",
        "title": "Pages",
        "type": "array",
        "examples": [
          "licence",
          "lcao"
        ],
        "items": {
          "type": "string"
        }
      },
      "parcours": {
        "description": "Le code du parcours (filière sans l'année) du cours.",
        "examples": [
          "mathinfo",
          "math"
        ],
        "title": "Parcours",
        "type": "string"
      },
      "title": {
        "description": "Le titre du groupe, contient le parcours et l'année.",
        "examples": [
          "MathInfo 1"
        ],
        "title": "Titre",
        "type": "string"
      },
      "year": {
        "description": "Le code de l'année du groupe.",
        "examples": [
          "l1",
          "l2"
        ],
        "title": "Année",
        "type": "string"
      }
    },
    "required": [
      "code",
      "title",
      "label",
      "parcours",
      "year"
    ]
  },
  "title": "Schema for calendars",
  "type": "array"
}

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-mathinfo.json
[
   {"code": "14381", "title": "MathInfo 1", "label": "MathInfo1", "parcours": "mathinfo", "year": "l1", "page": ["licence"]} ,
   {"code": "14383", "title": "MathInfo 2", "label": "MathInfo2", "parcours": "mathinfo", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-mathinfol1", "title": "AncVersion", "label": "obsolète", "parcours": "mathinfo", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "AnglaisL3ufrmath.1", "title": "L3MFA Anglais", "label": "Angl.1", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.2", "title": "L3MFA Anglais", "label": "Angl.2", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.3", "title": "L3MFA Anglais", "label": "Angl.3", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.4", "title": "L3MFA Anglais", "label": "Angl.4", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.5", "title": "L3MFA Anglais", "label": "Angl.5", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.6", "title": "L3MFA Anglais", "label": "Angl.6", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "22129", "title": "MathInfo1", "label": "MathInfo1", "parcours": "mathinfo", "year": "l2", "page": ["licence"]} ,
   {"code": "22130", "title": "MathInfo2", "label": "MathInfo2", "parcours": "mathinfo", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-mathinfol2", "title": "AncVersion", "label": "obsolète", "parcours": "mathinfo", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "22133", "title": "L3MathInfo1", "label": "MathInfo1", "parcours": "mathinfo", "year": "l3", "page": ["licence"]} ,
   {"code": "obso-mathinfol3", "title": "AncVersion", "label": "obsolète", "parcours": "mathinfo", "year": "l3", "page": ["licence"], "annexe": true} ,
   {"code": "59387", "title": "M1 Maths Info Crypto", "label": "M1 MIC", "parcours": "mathinfo", "year": "m1", "page": ["licence"]} ,
   {"code": "47495", "title": "M1 Maths Info Data Science", "label": "M1 MISD", "parcours": "mathinfo", "year": "m1", "page": ["licence"]} ,
   {"code": "obso-mathinfom1", "title": "AncVersion", "label": "obsolète", "parcours": "mathinfo", "year": "m1", "page": ["licence"], "annexe": true} ,
   {"code": "59404", "title": "M2 Maths Info Crypto", "label": "M2 MIC", "parcours": "mathinfo", "year": "m2", "page": ["licence"]} ,
   {"code": "59188", "title": "M2 Maths Info Science Donnees", "label": "M2 MISD", "parcours": "mathinfo", "year": "m2", "page": ["licence"]} ,
   {"code": "obso-mathinfom2", "title": "AncVersion", "label": "obsolète", "parcours": "mathinfo", "year": "m2", "page": ["licence"], "annexe": true} ,
   {"code": "1200", "title": "Salle TP UFR Math", "label": "TP 2004", "parcours": "mathinfo", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1515", "title": "Salle TP UFR Math", "label": "TP 2005", "parcours": "mathinfo", "year": "salles TP", "page": ["licence"]} ,
   {"code": "1279", "title": "Salle TP UFR Math", "label": "TP 2006", "parcours": "mathinfo", "year": "salles TP", "page": ["licence"]} ,
   {"code": "3839.tutorat", "title": "Tutorat", "label": "Tutorat", "parcours": "mathinfo", "year": "ufr-divers", "page": ["licence"]}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-miashs.json
[
   {"code": "14422", "title": "MiashsEco1", "label": "ECO1", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14423", "title": "MiashsEco2", "label": "ECO2", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14425", "title": "MiashsEco3", "label": "ECO3", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14426", "title": "MiashsEco4", "label": "ECO4", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14415", "title": "MiashsGéo", "label": "GEO", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14418", "title": "MiashsHis", "label": "HIST", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14419", "title": "MiashsLing", "label": "LING", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "14420", "title": "MiashsSoc", "label": "SOCIO", "parcours": "miashs", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-miashsl1", "title": "AncVersion", "label": "obsolète", "parcours": "miashs", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "11217.sem2", "title": "AnglaisL2fusionnes", "label": "Angl.L2", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14463", "title": "MiashsEco1", "label": "ECO1", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14464", "title": "MiashsEco2", "label": "ECO2", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14466", "title": "MiashsEco3", "label": "ECO3", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14470", "title": "MiashsGéog", "label": "GEO", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14471", "title": "MiashsHisto", "label": "HIST", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14472", "title": "MiashsLingu", "label": "LING", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "14475", "title": "MiashsSocio", "label": "SOCIO", "parcours": "miashs", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-miashsl2", "title": "AncVersion", "label": "obsolète", "parcours": "miashs", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "5666.sem2", "title": "AnglaisL3fusionnes", "label": "Angl.L3", "parcours": "miashs", "year": "l3", "page": ["licence"]} ,
   {"code": "14504", "title": "MiashsECO1", "label": "L3Miashs1", "parcours": "miashs", "year": "l3", "page": ["licence"]} ,
   {"code": "14505", "title": "MiashsECO2", "label": "L3Miashs2", "parcours": "miashs", "year": "l3", "page": ["licence"]} ,
   {"code": "obso-miashsl3", "title": "AncVersion", "label": "obsolète", "parcours": "miashs", "year": "l3", "page": ["licence"], "annexe": true} ,
   {"code": "46992", "title": "L3 MIASHS - Prof des Ecoles", "label": "L3 PDE", "parcours": "miashs", "year": "l3-pde", "page": ["licence"]} ,
   {"code": "14419", "title": "MiashsLing", "label": "L1Miashs", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "37117", "title": "uelibreling", "label": "Option L1-L2", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "sallesuelibreling.LL012Y", "title": "uelibreling", "label": "Option_L1-L2", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "37266", "title": "inititation ling. gen", "label": "Init.Ling.Gen", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "14472", "title": "MiashsLingu", "label": "L2Miashs", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "11217.sem2", "title": "AnglaisL2fusionnes", "label": "Angl.L2", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "14504", "title": "MiashsLing1", "label": "L3Miashs1", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "14505", "title": "MiashsLing2", "label": "L3Miashs2", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "4549", "title": "MiashsLinginfo", "label": "L3Miashs-ling", "parcours": "miashs", "year": "ling", "page": ["licence"], "annexe": true} ,
   {"code": "5271.l3sdl_l3miashs", "title": "L3SDL-LI", "label": "L3SDL-LI", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "5666.sem2", "title": "AnglaisL3fusionnes", "label": "Angl.L3", "parcours": "miashs", "year": "ling", "page": ["licence"]} ,
   {"code": "3839.tutorat", "title": "Tutorat", "label": "Tutorat", "parcours": "miashs", "year": "ufr-divers", "page": ["licence"]} ,
   {"code": "sesmiashs1", "title": "", "label": "SES-Gr1", "parcours": "miashs", "year": "l3"} ,
   {"code": "sesmiashs2", "title": "", "label": "SES-Gr2", "parcours": "miashs", "year": "l3"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-chimie.json
[
   {"code": "5633", "title": "CHIM1", "label": "CHIM1", "parcours": "chimie", "year": "l1", "page": ["licence"]} ,
   {"code": "5634", "title": "CHIM2", "label": "CHIM2", "parcours": "chimie", "year": "l1", "page": ["licence"]} ,
   {"code": "5635", "title": "CHIM3", "label": "CHIM3", "parcours": "chimie", "year": "l1", "page": ["licence"]} ,
   {"code": "5636", "title": "CHIM4", "label": "CHIM4", "parcours": "chimie", "year": "l1", "page": ["licence"]} ,
   {"code": "5637", "title": "L1CHIMBio1", "label": "CHIM BIO1", "parcours": "chimie", "year": "l1", "page": ["licence"]} ,
   {"code": "obso-chiml1", "title": "AncVersion", "label": "obsolète", "parcours": "chimie", "year": "l1", "page": ["licence"], "annexe": true} ,
   {"code": "5638", "title": "CHIM1", "label": "CHIM1", "parcours": "chimie", "year": "l2", "page": ["licence"]} ,
   {"code": "5639", "title": "CHIM2", "label": "CHIM2", "parcours": "chimie", "year": "l2", "page": ["licence"]} ,
   {"code": "5640", "title": "CHIM3", "label": "CHIM3", "parcours": "chimie", "year": "l2", "page": ["licence"]} ,
   {"code": "5641", "title": "L2CHIMBIO1", "label": "CHIM BIO1", "parcours": "chimie", "year": "l2", "page": ["licence"]} ,
   {"code": "obso-chiml2", "title": "AncVersion", "label": "obsolète", "parcours": "chimie", "year": "l2", "page": ["licence"], "annexe": true} ,
   {"code": "5711", "title": "L3CHIM1", "label": "CHIM1", "parcours": "chimie", "year": "l3", "page": ["licence"]} ,
   {"code": "5712", "title": "L3CHIM2", "label": "CHIM2", "parcours": "chimie", "year": "l3", "page": ["licence"]} ,
   {"code": "5713", "title": "L3CHIM3", "label": "CHIM3", "parcours": "chimie", "year": "l3", "page": ["licence"]} ,
   {"code": "5715", "title": "L3CHIM4", "label": "CHIM4", "parcours": "chimie", "year": "l3", "page": ["licence"]} ,
   {"code": "8160", "title": "L3CHIMBIO", "label": "CHIM BIO1", "parcours": "chimie", "year": "l3", "page": ["licence"]} ,
   {"code": "5708", "title": "M1 Chim Gr1", "label": "M1-PhysC1", "parcours": "chimie", "year": "m1", "page": ["licence"]} ,
   {"code": "5709", "title": "M1 Chim Gr2", "label": "M1-PhysC2", "parcours": "chimie", "year": "m1", "page": ["licence"]} ,
   {"code": "6065", "title": "M1 Chim Gr3", "label": "M1-MolC1", "parcours": "chimie", "year": "m1", "page": ["licence"]} ,
   {"code": "6200", "title": "M1 Chim Gr4", "label": "M1-MolC2", "parcours": "chimie", "year": "m1", "page": ["licence"]} ,
   {"code": "42638", "title": "M1 Chim RE Saints-Peres", "label": "M1-MolC3", "parcours": "chimie", "year": "m1", "page": ["licence"], "annexe": true} ,
   {"code": "21593", "title": "M1 Chim RE", "label": "M1-Chim RE", "parcours": "chimie", "year": "m1-re", "page": ["licence"]} ,
   {"code": "6020", "title": "M1 Chim RE", "label": "M1-Chim RE Gr1", "parcours": "chimie", "year": "m1-re", "page": ["licence"]} ,
   {"code": "8390", "title": "M1 Chim RE", "label": "M1-Chim RE Gr2", "parcours": "chimie", "year": "m1-re", "page": ["licence"]} ,
   {"code": "8391", "title": "M1 Chim RE", "label": "M1-Chim RE Gr3", "parcours": "chimie", "year": "m1-re", "page": ["licence"]} ,
   {"code": "8392", "title": "M1 Chim RE", "label": "M1-Chim RE Gr4", "parcours": "chimie", "year": "m1-re", "page": ["licence"]} ,
   {"code": "6213", "title": "M2 Chim Gr1", "label": "M2-CHENS", "parcours": "chimie", "year": "m2", "page": ["licence"]} ,
   {"code": "6214", "title": "M2 Chim Gr2", "label": "M2-SAFE", "parcours": "chimie", "year": "m2", "page": ["licence"]} ,
   {"code": "6259", "title": "M2 Chim Gr3", "label": "M2-PCLife", "parcours": "chimie", "year": "m2", "page": ["licence"]} ,
   {"code": "6215", "title": "M2 Chim Gr4", "label": "M2-OBMC", "parcours": "chimie", "year": "m2", "page": ["licence"]} ,
   {"code": "6342", "title": "M2 Chim", "label": "M2-Chim.Gr5", "parcours": "chimie", "year": "m2", "page": ["licence"], "annexe": true} ,
   {"code": "6500", "title": "M2 Chim", "label": "M2-Chim.Gr6", "parcours": "chimie", "year": "m2", "page": ["licence"], "annexe": true}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-zz-halle.json
[
   {"code": "1276", "title": "Halle - 11E - 147", "label": "11E", "parcours": "zz-halle", "year": "Amphis cinema"} ,
   {"code": "1418", "title": "Halle - 7C - 147", "label": "7C", "parcours": "zz-halle", "year": "Amphis cinema"} ,
   {"code": "1274", "title": "Halle - 10E - 147", "label": "10E", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1257", "title": "Halle - 12E - 147", "label": "12E", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1182", "title": "Halle - 4C - 147", "label": "4C", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1219", "title": "Halle - 5C - 147", "label": "5C", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1298", "title": "Halle - 6C - 147", "label": "6C", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1273", "title": "Halle - 9E - 147", "label": "9E", "parcours": "zz-halle", "year": "Amphis"} ,
   {"code": "1416", "title": "Halle - 13E - 238", "label": "13E", "parcours": "zz-halle", "year": "Amphis 200p"} ,
   {"code": "1020", "title": "Halle - 1A - 276 - Ernest Vilgrain", "label": "1A", "parcours": "zz-halle", "year": "Amphis 200p"} ,
   {"code": "1013", "title": "Halle - 2A - 276", "label": "2A", "parcours": "zz-halle", "year": "Amphis 200p"} ,
   {"code": "1154", "title": "Halle - 8C - 238", "label": "8C", "parcours": "zz-halle", "year": "Amphis 200p"} ,
   {"code": "1271", "title": "Halle - 3B - 132", "label": "3B", "parcours": "zz-halle", "year": "Amphis plats"} ,
   {"code": "1245", "title": "Halle - 580F - 90", "label": "580F", "parcours": "zz-halle", "year": "Amphis plats"} ,
   {"code": "1469", "title": "Halle - 165E - 52", "label": "165E", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1687", "title": "Halle - 278F - 52", "label": "278F", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1498", "title": "Halle - 279F - 52", "label": "279F", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1619", "title": "Halle - 378F - 52", "label": "378F", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1686", "title": "Halle - 410B - 52", "label": "410B", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1316", "title": "Halle - 478F - 52", "label": "478F", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1084", "title": "Halle - 479F - 52", "label": "479F", "parcours": "zz-halle", "year": "Salles 52p"} ,
   {"code": "1482", "title": "Halle - 379F - 60", "label": "379F", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1615", "title": "Halle - 027C - 70", "label": "027C", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1368", "title": "Halle - 064E - 70", "label": "064E", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1489", "title": "Halle - 226C - 70", "label": "226C", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1102", "title": "Halle - 227C - 69", "label": "227C", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1551", "title": "Halle - 264E - 70", "label": "264E", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1225", "title": "Halle - 265E - 70", "label": "265E", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1520", "title": "Halle - 418C - 70", "label": "418C", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1552", "title": "Halle - 419C - 70", "label": "419C", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1510", "title": "Halle - 470E - 70", "label": "470E", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1620", "title": "Halle - 471E - 70", "label": "471E", "parcours": "zz-halle", "year": "Salles 60-70p"} ,
   {"code": "1300", "title": "Halle - 234C - 84", "label": "234C", "parcours": "zz-halle", "year": "Salles 84p"} ,
   {"code": "1664", "title": "Halle - 247E - 84", "label": "247E", "parcours": "zz-halle", "year": "Salles 84p"}
]

=== l-pommeret/EDT-LOGOS1/csvcalendars/calendars-ingemath.json
[
   {"code": "AnglaisL3ufrmath.1", "title": "L3MFA Anglais", "label": "Angl.1", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.2", "title": "L3MFA Anglais", "label": "Angl.2", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.3", "title": "L3MFA Anglais", "label": "Angl.3", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.4", "title": "L3MFA Anglais", "label": "Angl.4", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.5", "title": "L3MFA Anglais", "label": "Angl.5", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "AnglaisL3ufrmath.6", "title": "L3MFA Anglais", "label": "Angl.6", "parcours": "ingemath", "year": "l3", "page": ["licence"]} ,
   {"code": "22145", "title": "INGEMath", "label": "IngeMath1", "parcours": "ingemath", "year": "l3", "page": ["licence"]}
]
